algoritmo "semnome"
var
   num1, num2, num3 :real
inicio
      escreva ("Digite o primeiro número: ")
      leia (num1)
      escreva ("Digite o segundo número: ")
      leia (num2)
      escreva ("Digite o terceiro número: ")
      leia (num3)
      se (num1+num2+num3) > 50 entao
         escreva ("A soma dos números é maior que 50. ")
      senao
         escreva ("A soma dos números não é maior que 50. ")
      fimse
fimalgoritmo
